# Generated by Django 5.1.1 on 2024-12-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_wishlist_customer_alter_wishlist_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='products',
        ),
    ]
