# Generated by Django 5.1.1 on 2025-01-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_product_wishlist_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='in_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
