# Generated by Django 5.1.6 on 2025-02-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_in_cart_product_in_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
