# Generated by Django 5.1.6 on 2025-03-04 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_product_in_cart_remove_product_in_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('stars_rating', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('remain_stars', models.PositiveIntegerField(blank=True, default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
    ]
