# Generated by Django 5.1.6 on 2025-02-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_order_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingadrress',
            name='email',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
