# Generated by Django 5.1.6 on 2025-02-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_payment_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadrress',
            old_name='country',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='shippingadrress',
            old_name='city',
            new_name='town',
        ),
        migrations.RemoveField(
            model_name='shippingadrress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shippingadrress',
            name='zipcode',
        ),
    ]
